### ISSUE TITLE
command find_family fails

### ISSUE THREAD

**Issue by lucaz88** [epruesse/SINA#52]
Dear Elmar,

I am trying the parallel version of sina (1.4.0) with a set of ~22,000 full 16S sequences but after 1d of running I start to get a lot of warnings like:
```
AISC_SET_ERROR: CONNECTION PROBLEMS
Unable to execute find_family command on pt-server
Retring...
```
and eventually, an abort message:
`No retries left; aborting.`

How can I solve the problem?
The command I am running is:
`sina -i derep.fasta -o derep_aln.fasta --meta-fmt csv --db silva/ARB/SILVA_132_SSURef_12_12_17_opt.arb --search --search-min-sim 0.865 --search-db silva/ARB/SILVA_132_SSURef_12_12_17_opt.arb --lca-fields tax_slv --num-pts 8`

I installed sina using conda in a Ubuntu 16.04.1 environment. The computer has 28 cores and 512Gb of RAM.
Thanks for your help!

**Comment by epruesse** [comment]
@lucaz88 That happens when one of the ARB PT servers crashes. They tend to do that when they run for more than a few hours at a time. It's been a problem for ever, but it's so consuming to reproduce the error that I've never been able to come up with a solid workaround. It's the a big part of  why I've been busy building an alternative, internal sequence search into SINA.

The next version of SINA will have this fully functional. I'll finish the thing this month. If you can't wait that long - you can split your job two ways: 

 1. Running the search & classify in a separate process (run once without the `--search` options, then run on the aligned sequences using `--prealigned` instead of `--db ref.arb`).   
 2. Splitting your input FASTA into batches small enough to complete within an hour. If you do that, given the power of your box, you can also run multiple instances of SINA at once.

Also --- the `--search` part doesn't run in parallel yet and will be the limiting factor with your data.

Again - I'm sorry, but there is no easy fix for this. I'll ping you here as soon as I have a version that doesn't need the PT server at all.

**Comment by lucaz88** [comment]
Many thanks! I will start trying your first suggestion.
Looking forward to the new version of sina!!
