### ISSUE TITLE
Printing Full Phylogeny

### ISSUE THREAD

**Issue by mbcouger** [epruesse/SINA#75]
Hello Sina Dev Group, 

I am using SINA to classify 16s seqs, I am running the following commmand with the newest Silva release:
./sina -i Ecolittest.fasta --db SILVA_132_SSURef_NR99_13_12_17_opt.arb -p 1 --meta-fmt CSV -o tesyh --search-db SILVA_132_SSURef_NR99_13_12_17_opt.arb --lca-fields tax_slv

Can you please point me on how to print the full phyologeny of the alingments (Domain> Species)

Many Thanks,
Brian

**Comment by epruesse** [comment]
Try using `--search-max-result 1` - that will work like a best-BLAST and just give you the full classification for that hit.

**Comment by IBG-5-KIT** [comment]
but what if one does not want a "best-BLAST" but the actual Least common ancestor (LCA) results. Is there a nice way to get the results in table format, similar to the classification output of the[ Silva ACT webservice](https://www.arb-silva.de/aligner)?

(because the best-hit is often not entirely reliable)

**Comment by epruesse** [comment]
Yes, there is now. Try the newest version with `-o results.csv` and `-f` set to the fields you want to have.

**Comment by epruesse** [comment]
SINA 1.7.0 binaries should be up within the hour, and the Bioconda packages within the day. Give those a shot and reopen this if necessary.
